# Generated by Django 4.1.2 on 2022-10-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0002_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personCode', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
