# Generated by Django 4.1.2 on 2022-11-10 14:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0003_attendance'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='inspect',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.equipment'),
        ),
    ]
