# Generated by Django 4.1.2 on 2022-11-10 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0004_equipment_profile_inspect'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='inspect',
        ),
        migrations.AddField(
            model_name='profile',
            name='inspect',
            field=models.ManyToManyField(blank=True, to='websites.equipment'),
        ),
    ]
