# Generated by Django 4.1.2 on 2022-11-10 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0005_remove_profile_inspect_profile_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='inspect',
            field=models.ManyToManyField(blank=True, related_name='inspection', to='websites.equipment'),
        ),
    ]
