# Generated by Django 4.1.2 on 2022-11-21 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0007_rename_profile_profiles'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='qr_code',
            field=models.ImageField(blank=True, upload_to='qr_codes'),
        ),
    ]
