# Generated by Django 4.1.2 on 2022-11-21 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0008_profiles_qr_code'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Website',
        ),
    ]
