# Generated by Django 4.1.2 on 2022-11-21 13:58

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0009_delete_website'),
    ]

    operations = [
        migrations.AddField(
            model_name='profiles',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
