# Generated by Django 4.1.2 on 2022-11-21 22:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0010_profiles_created_at'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='profiles',
            unique_together={('email',)},
        ),
    ]
