# Generated by Django 4.1.2 on 2022-11-24 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0015_alter_attendance_timeoutcreated'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='timeOutCreated',
            field=models.DateTimeField(default=''),
        ),
    ]
