# Generated by Django 4.1.2 on 2022-11-24 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0018_alter_attendance_timeoutcreated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='attendance',
            old_name='timeInCreated',
            new_name='created',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='timeOutCreated',
        ),
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('time in', 'Time In'), ('time out', 'Time out')], max_length=255),
        ),
    ]
