# Generated by Django 4.1.2 on 2022-11-25 20:16

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0020_remove_attendance_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('time in', 'Time In'), ('time out', 'Time Out')], default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
    ]
