# Generated by Django 4.1.2 on 2022-11-27 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0021_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='created',
            field=models.DateTimeField(),
        ),
    ]
