# Generated by Django 4.1.2 on 2022-11-27 23:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0022_alter_attendance_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attendance',
            options={'ordering': ['-created']},
        ),
        migrations.RemoveField(
            model_name='profiles',
            name='inspect',
        ),
        migrations.AddField(
            model_name='attendance',
            name='inspect',
            field=models.ManyToManyField(blank=True, related_name='inspection', to='websites.equipment'),
        ),
    ]
