# Generated by Django 4.1.2 on 2022-11-29 04:58

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0023_alter_attendance_options_remove_profiles_inspect_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='personCode',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
