# Generated by Django 4.1.2 on 2022-11-29 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0024_alter_attendance_personcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='personCode',
            field=models.CharField(max_length=200),
        ),
    ]
