# Generated by Django 4.1.2 on 2022-12-21 12:38

from django.db import migrations, models
import django_cryptography.fields


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0025_alter_attendance_personcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='personCode',
            field=django_cryptography.fields.encrypt(models.CharField(max_length=200)),
        ),
    ]
