# Generated by Django 4.1.2 on 2022-12-21 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0027_alter_attendance_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='personCode',
            field=models.CharField(max_length=200),
        ),
    ]
