# Generated by Django 4.1.2 on 2022-12-22 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0031_alter_attendance_personcode_alter_attendance_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.profiles'),
        ),
    ]
