# Generated by Django 4.1.2 on 2023-01-27 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0035_mymodel_created_at_alter_mymodel_my_json_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='created_at',
            field=models.DateTimeField(),
        ),
    ]
