# Generated by Django 4.1.2 on 2023-01-27 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0036_alter_mymodel_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='inspect',
            field=models.ManyToManyField(blank=True, related_name='modelinspect', to='websites.equipment'),
        ),
    ]
