# Generated by Django 4.1.2 on 2023-01-28 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0037_mymodel_inspect'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymodel',
            name='my_json_field',
            field=models.JSONField(default=dict),
        ),
    ]
