# Generated by Django 4.1.2 on 2023-01-28 15:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('websites', '0038_alter_mymodel_my_json_field'),
    ]

    operations = [
        migrations.AddField(
            model_name='mymodel',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='websites.profiles'),
        ),
    ]
