# Generated by Django 4.1.2 on 2023-01-05 08:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='user',
            name='bio',
        ),
        migrations.AddField(
            model_name='user',
            name='code',
            field=models.UUIDField(default=uuid.uuid4, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='user',
            name='codeCreated',
            field=models.DateTimeField(null=True),
        ),
    ]
