# Generated by Django 4.1.2 on 2023-01-05 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0002_remove_user_avatar_remove_user_bio_user_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.UUIDField(null=True, unique=True),
        ),
    ]
