# Generated by Django 4.1.2 on 2023-01-05 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0003_alter_user_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='code',
            field=models.UUIDField(null=True),
        ),
    ]
