# Generated by Django 4.1.2 on 2023-01-13 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminportal', '0006_alter_user_auth'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='adminAccess',
            field=models.BooleanField(default=False),
        ),
    ]
